apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice-deployment
  namespace: boutique
  labels:
    app: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
      - name: recommendationservicecontainer
        image: pavankumarkothala31/recommendationservice:v1
        ports:
        - containerPort: 8080
        readinessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          grpc:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: PORT
          value: "8080"
        - name: PRODUCT_CATALOG_SERVICE_ADDR
          value: "productcatalogservice:3550"
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: boutique
spec:
  selector:
    app: recommendationservice
  ports:
  - port: 8080
    targetPort: 8080
